

services:


  # zookeeper:
  #   image: bitnami/zookeeper:3.9
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   healthcheck:
  #     test: ["CMD", "bash", "-c", "echo stat | nc localhost 2181 | grep Mode"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5


  # kafka:
  #   image: bitnami/kafka:3.7
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   healthcheck:
  #     test: ["CMD", "bash", "-c", "kafka-topics.sh --bootstrap-server localhost:9092 --list | cat"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10


  # kafka-ui:
  #   image: bitnami/kafka-ui:latest
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - KAFKA_SERVER=kafka:9092
  #   depends_on:
  #     - kafka


  # ingestor:
  #   build: ./services/ingestor
  #   env_file: 
  #     - ./.env
  #   environment:
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   restart: unless-stopped


  # processor:
  #   build: ./services/processor
  #   env_file: 
  #     - ./.env
  #   environment:
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   restart: unless-stopped

  processor:
    build: ./services/processor
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # airflow:
  #   image: apache/airflow:2.9.3
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__CORE__LOAD_EXAMPLES=False
  #     - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
  #   volumes:
  #     - ./dags:/usr/local/airflow/dags
  #     - ./logs:/usr/local/airflow/logs
  #     - ./plugins:/usr/local/airflow/plugins
  #   ports:
  #     - "8082:8080"
  #   command: >
  #     bash -c "
  #     airflow db init &&
  #     airflow users create --username admin --firstname Admin --lastname User --role Admin --email


  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10


  superset:
    image: apache/superset:5.0.0
    ports:
      - "8088:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "your_secret_key"
      ADMIN_USERNAME: "admin"
      ADMIN_FIRSTNAME: "Admin"
      ADMIN_LASTNAME: "User"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"
    user: root
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/bin/bash", "-c", "apt update && apt install -y gcc libpq-dev python3-dev pkg-config && uv pip install psycopg2-binary && superset db upgrade && superset fab create-admin --username $ADMIN_USERNAME --firstname $ADMIN_FIRSTNAME --lastname $ADMIN_LASTNAME --email $ADMIN_EMAIL --password $ADMIN_PASSWORD || true && superset init && superset run -h 0.0.0.0 -p 8088"]


volumes:
  pgdata: